INSERT INTO "taskmanager_alert" VALUES(1,8,6,'','','{"url": "/taskmanager/patients/6/history/#session_5", "msgtext": "2/17 @ 415pm", "appt_type": "heart doctor appt.", "contact_no": "310-794-2474"}','2011-02-16 11:16:59.589105');
INSERT INTO "taskmanager_alert" VALUES(2,8,4,'','','{"url": "/taskmanager/patients/4/history/#session_11", "msgtext": "2/19/2011.", "appt_type": "blood test", "contact_no": "310-794-2474", "requires_fasting": "on"}','2011-02-17 12:46:37.795967');
INSERT INTO "taskmanager_alert" VALUES(3,1,4,'','','{"url": "/taskmanager/patients/4/history/#session_23", "feedback": "good"}','2011-02-20 09:15:52.780742');
INSERT INTO "taskmanager_alert" VALUES(4,1,2,'','','{"url": "/taskmanager/patients/2/history/#session_17", "feedback": "good"}','2011-02-21 15:02:10.578104');
INSERT INTO "taskmanager_alert" VALUES(5,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 287, in ajax_POST_exec\n    t = eval(module)(smsuser, args)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/appointment_request.py\", line 119, in __init__\n    super(AppointmentRequest, self).setinteraction(graph=self.graph, initialnode=m_initial, label=''interaction'')\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/task.py\", line 12, in setinteraction\n    self.interaction = sms.Interaction(graph=graph, initialnode=initialnode, label=label)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 100, in __init__\n    Interaction.isvalid(graph, initialnode)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 136, in isvalid\n    raise ValueError(\"bad mapping.\")\nValueError: bad mapping.\n", "name": "ValueError", "module": "tasks.appointment_request.AppointmentRequest"}','2011-02-21 15:10:28.828035');
INSERT INTO "taskmanager_alert" VALUES(6,1,8,'','','{"url": "/taskmanager/patients/8/history/#session_19", "feedback": "I''m confused why do I have to type Resp why not just feedback?"}','2011-02-21 20:46:51.518200');
INSERT INTO "taskmanager_alert" VALUES(7,1,1,'','','{"url": "/taskmanager/patients/1/history/#session_31", "feedback": "wonderful! & testing &"}','2011-02-22 16:30:58.007176');
INSERT INTO "taskmanager_alert" VALUES(8,8,5,'','','{"url": "/taskmanager/patients/5/history/#session_32", "msgtext": "fine", "appt_type": "bone density test", "contact_no": "310-794-2474", "appt_date": "02/22/2011 10:00AM"}','2011-02-23 16:19:44.410255');
INSERT INTO "taskmanager_alert" VALUES(9,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-03 15:00:27.235118');
INSERT INTO "taskmanager_alert" VALUES(10,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-03 15:00:27.555139');
INSERT INTO "taskmanager_alert" VALUES(11,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-04 10:06:00.782241');
INSERT INTO "taskmanager_alert" VALUES(12,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-04 10:06:01.115572');
INSERT INTO "taskmanager_alert" VALUES(13,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-04 17:00:03.827829');
INSERT INTO "taskmanager_alert" VALUES(14,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-04 17:00:04.093649');
INSERT INTO "taskmanager_alert" VALUES(15,3,1,'','','{"url": "/taskmanager/patients/1/history/#session_35", "contact_no": "6267203312", "appt_type": "bone density test", "appt_date": "03/04/2011 11:00AM"}','2011-03-04 17:22:43.549173');
INSERT INTO "taskmanager_alert" VALUES(16,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-07 15:33:20.215546');
INSERT INTO "taskmanager_alert" VALUES(17,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-07 15:33:20.457546');
INSERT INTO "taskmanager_alert" VALUES(18,8,10,'','','{"url": "/taskmanager/patients/10/history/#session_36", "msgtext": "N", "appt_type": "Echo test (ultrasound-of-heart)", "contact_no": "3107941710"}','2011-03-08 15:34:59.992929');
INSERT INTO "taskmanager_alert" VALUES(19,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-09 15:00:01.576473');
INSERT INTO "taskmanager_alert" VALUES(20,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-09 15:00:01.842843');
INSERT INTO "taskmanager_alert" VALUES(21,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-10 13:17:36.710464');
INSERT INTO "taskmanager_alert" VALUES(22,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-10 13:17:37.005841');
INSERT INTO "taskmanager_alert" VALUES(23,8,1,'','','{"url": "/taskmanager/patients/1/history/#session_38", "msgtext": "next Tuesday at 3pm", "appt_type": "bone density test", "contact_no": "6267203312"}','2011-03-10 13:23:00.131339');
INSERT INTO "taskmanager_alert" VALUES(24,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-10 20:00:09.646798');
INSERT INTO "taskmanager_alert" VALUES(25,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-10 20:00:09.945687');
INSERT INTO "taskmanager_alert" VALUES(26,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-11 10:15:11.053536');
INSERT INTO "taskmanager_alert" VALUES(27,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-11 10:15:11.345273');
INSERT INTO "taskmanager_alert" VALUES(28,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-11 18:15:14.635938');
INSERT INTO "taskmanager_alert" VALUES(29,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-11 18:15:14.986338');
INSERT INTO "taskmanager_alert" VALUES(30,8,9,'','','{"contact_no": "310-825-4073", "msgtext": "postponed till 3-16", "requires_fasting": "on", "url": "/taskmanager/patients/9/history/#session_41", "appt_type": "blood test", "appt_date": "03/11/2011 12:15PM"}','2011-03-12 18:23:55.056854');
INSERT INTO "taskmanager_alert" VALUES(31,1,9,'','','{"url": "/taskmanager/patients/9/history/#session_41", "feedback": "postponed till 3/16"}','2011-03-13 18:25:59.752562');
INSERT INTO "taskmanager_alert" VALUES(32,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-14 20:00:02.685773');
INSERT INTO "taskmanager_alert" VALUES(33,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-14 20:00:03.001461');
INSERT INTO "taskmanager_alert" VALUES(34,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04166c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-15 13:00:05.409464');
INSERT INTO "taskmanager_alert" VALUES(35,6,6,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xa04162c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-15 13:00:05.708344');
INSERT INTO "taskmanager_alert" VALUES(36,1,1,'','','{"url": "/taskmanager/patients/1/history/#session_44", "feedback": "it went well, despite the dst mixup ~_~N"}','2011-03-15 21:13:48.114617');
INSERT INTO "taskmanager_alert" VALUES(37,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 287, in ajax_POST_exec\n    t = eval(module)(smsuser, args)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 19, in __init__\n    if ''script'' not in self.args:\nAttributeError: ''XmlTask'' object has no attribute ''args''\n", "name": "AttributeError", "module": "tasks.xmltask.XmlTask"}','2011-03-30 09:57:16.913539');
INSERT INTO "taskmanager_alert" VALUES(38,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 287, in ajax_POST_exec\n    t = eval(module)(smsuser, args)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 40, in __init__\n    initial = self._parse_message(self.graph, root)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 185, in _parse_message\n    text = context.text if ''template'' not in content.attrib else None\nNameError: global name ''context'' is not defined\n", "name": "NameError", "module": "tasks.xmltask.XmlTask"}','2011-03-30 09:58:16.874267');
INSERT INTO "taskmanager_alert" VALUES(39,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 287, in ajax_POST_exec\n    t = eval(module)(smsuser, args)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 40, in __init__\n    initial = self._parse_message(self.graph, root)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 216, in _parse_message\n    match_callback=getattr(self, response.get(''matcher'')),\nTypeError: getattr(): attribute name must be string\n", "name": "TypeError", "module": "tasks.xmltask.XmlTask"}','2011-03-30 09:59:46.889470');
INSERT INTO "taskmanager_alert" VALUES(40,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 287, in ajax_POST_exec\n    t = eval(module)(smsuser, args)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 40, in __init__\n    initial = self._parse_message(self.graph, root)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 221, in _parse_message\n    label=response.get(''label''))\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 30, in __init__\n    raise ValueError(''Response requires a unique label string.'')\nValueError: Response requires a unique label string.\n", "name": "ValueError", "module": "tasks.xmltask.XmlTask"}','2011-03-30 10:01:46.920073');
INSERT INTO "taskmanager_alert" VALUES(41,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xa67834c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:28:12.153250');
INSERT INTO "taskmanager_alert" VALUES(42,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xa67834c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:30:16.142319');
INSERT INTO "taskmanager_alert" VALUES(43,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 44, in handle\n    response = self.tm.recv(message)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 617, in recv\n    if self.app.createdbuserandtask(rmessage):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 184, in createdbuserandtask\n    keyword = eval(fn)\n  File \"<string>\", line 1, in <module>\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/xmltask.py\", line 70, in get_user_init_string\n    return self.taskprefix\nNameError: global name ''self'' is not defined\n", "name": "NameError", "module": "n/a"}','2011-03-30 10:30:47.383670');
INSERT INTO "taskmanager_alert" VALUES(44,8,1,'','','{"msgtext": "greet good mang everything is swell"}','2011-03-30 10:30:47.474562');
INSERT INTO "taskmanager_alert" VALUES(45,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xad84acc>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:41:00.108915');
INSERT INTO "taskmanager_alert" VALUES(46,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xad84acc>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:43:04.174821');
INSERT INTO "taskmanager_alert" VALUES(47,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xad84acc>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:45:04.690362');
INSERT INTO "taskmanager_alert" VALUES(48,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0xad84acc>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:47:00.177232');
INSERT INTO "taskmanager_alert" VALUES(49,5,1,'','','{"traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 44, in handle\n    response = self.tm.recv(message)\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 617, in recv\n    if self.app.createdbuserandtask(rmessage):\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 184, in createdbuserandtask\n    keyword = eval(fn)\n  File \"<string>\", line 1, in <module>\nTypeError: unbound method get_user_init_string() must be called with XmlTask instance as first argument (got nothing instead)\n", "name": "TypeError", "module": "n/a"}','2011-03-30 10:47:51.171921');
INSERT INTO "taskmanager_alert" VALUES(50,8,1,'','','{"msgtext": "greet hey good"}','2011-03-30 10:47:51.280241');
INSERT INTO "taskmanager_alert" VALUES(51,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0x916b22c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:49:53.623108');
INSERT INTO "taskmanager_alert" VALUES(52,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0x916b22c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:51:57.622007');
INSERT INTO "taskmanager_alert" VALUES(53,6,1,'','','{"taskname": "<taskmanager.tasks.xmltask.XmlTask object at 0x916b22c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 10:52:20.041735');
INSERT INTO "taskmanager_alert" VALUES(54,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0x921e78c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 15:00:23.822308');
INSERT INTO "taskmanager_alert" VALUES(55,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0x921e78c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-30 19:00:54.427849');
INSERT INTO "taskmanager_alert" VALUES(56,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0xb362908c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-03-31 20:00:31.938961');
INSERT INTO "taskmanager_alert" VALUES(57,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0xb362908c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-01 00:00:54.062052');
INSERT INTO "taskmanager_alert" VALUES(58,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0x952986c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-01 12:00:34.254750');
INSERT INTO "taskmanager_alert" VALUES(59,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_reminder.AppointmentReminder object at 0x952986c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-01 16:00:53.661913');
INSERT INTO "taskmanager_alert" VALUES(60,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xb359144c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-01 20:00:07.754763');
INSERT INTO "taskmanager_alert" VALUES(61,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xb359144c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-02 20:00:58.417972');
INSERT INTO "taskmanager_alert" VALUES(62,3,11,'','','{"url": "/taskmanager/patients/11/history/#session_50", "contact_no": "13107942475", "appt_type": "blood test", "appt_date": "04/01/2011 02:00PM"}','2011-04-02 20:56:15.580543');
INSERT INTO "taskmanager_alert" VALUES(63,6,11,'','','{"taskname": "<taskmanager.tasks.appointment_followup.AppointmentFollowup object at 0xb359144c>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-02 20:56:15.857630');
INSERT INTO "taskmanager_alert" VALUES(64,6,9,'','','{"taskname": "<taskmanager.tasks.appointment_request.AppointmentRequest object at 0xb36458ac>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-04 12:30:21.954659');
INSERT INTO "taskmanager_alert" VALUES(65,6,9,'','','{"taskname": "<taskmanager.tasks.appointment_request.AppointmentRequest object at 0xb36458ac>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-05 12:30:58.906302');
INSERT INTO "taskmanager_alert" VALUES(66,6,9,'','','{"taskname": "<taskmanager.tasks.appointment_request.AppointmentRequest object at 0xb36458ac>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-06 12:31:59.214249');
INSERT INTO "taskmanager_alert" VALUES(67,6,9,'','','{"taskname": "<taskmanager.tasks.appointment_request.AppointmentRequest object at 0xb36458ac>", "traceback": "Traceback (most recent call last):\n  File \"/home/faisal/checkouts/cens/taskmanager/tasks/sms.py\", line 558, in save_curr_statemachine\n    self.app.savetask(statemachine.session_id, **d)\n  File \"/home/faisal/checkouts/cens/taskmanager/app.py\", line 336, in savetask\n    st = SerializedTask.objects.get(pk=s_session_id)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/manager.py\", line 132, in get\n    return self.get_query_set().get(*args, **kwargs)\n  File \"/usr/local/lib/python2.6/dist-packages/Django-1.2.1-py2.6.egg/django/db/models/query.py\", line 341, in get\n    % self.model._meta.object_name)\nDoesNotExist: SerializedTask matching query does not exist.\n", "name": "DoesNotExist"}','2011-04-07 12:32:54.410157');
